version: '3.9'

services:
  api:
    build: .
    container_name: ai_agent_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./credentials.json:/app/credentials.json:ro
    depends_on: []

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    environment:
      - WEBUI_NAME=AI Agent WebUI
    ports:
      - "8080:8080"
    volumes:
      - openwebui_data:/app/backend/data
    depends_on:
      - api

volumes:
  openwebui_data:
